### ISSUE TITLE
[kindle-crash] SearchFragment.startPromotionDownload: 391

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-android#179]
```
at java.util.Formatter$FormatSpecifierParser.unknownFormatConversionException(Formatter.java:2306)
    at java.util.Formatter$FormatSpecifierParser.advance(Formatter.java:2300)
    at java.util.Formatter$FormatSpecifierParser.parseConversionType(Formatter.java:2379)
    at java.util.Formatter$FormatSpecifierParser.parseArgumentIndexAndFlags(Formatter.java:2350)
    at java.util.Formatter$FormatSpecifierParser.parseFormatToken(Formatter.java:2283)
    at java.util.Formatter.doFormat(Formatter.java:1071)
    at java.util.Formatter.format(Formatter.java:1042)
    at java.util.Formatter.format(Formatter.java:1011)
    at java.lang.String.format(String.java:1999)
    at android.content.res.Resources.getString(Resources.java:366)
    at android.app.Fragment.getString(Fragment.java:802)
    at com.frostwire.android.gui.fragments.SearchFragment.startPromotionDownload(SearchFragment.java:391)
    at com.frostwire.android.gui.fragments.SearchFragment.access$700(SearchFragment.java:85)
    at com.frostwire.android.gui.fragments.SearchFragment$2.onPromotionClick(SearchFragment.java:183)
    at com.frostwire.android.gui.views.PromotionsView$1.onItemClick(PromotionsView.java:88)
    at android.widget.AdapterView.performItemClick(AdapterView.java:300)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1200)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3063)
    at android.widget.AbsListView$3.run(AbsListView.java:3808)
    at android.os.Handler.handleCallback(Handler.java:755)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5262)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by aldenml2** [comment]
@gubatron, sorry about this. Please could you add this secondary account to the frostwire repos temporarily (I can't access my usual "aldenml" account and I'm working with GitHub support to get it back).

**Comment by gubatron** [comment]
@aldenml2 only when I talk to you in person or over the phone. If you're not the true alden, nice try buddy.

**Comment by aldenml2** [comment]
Fine. No worries.

**Comment by aldenml2** [comment]
I can see why you're suspicious.

**Comment by aldenml2** [comment]
@gubatron, Would an email be OK?

**Comment by aldenml2** [comment]
@gubatron, it's only because I'm up in Fort Pierce with my cousins for Christmas/New Year. It's gonna make coming down to Miami or phoning you difficult...

**Comment by aldenml** [comment]
@gubatron I reported this user to github, after a while, we should remove these comments.
