### ISSUE TITLE
TorrentInfo/TransferManager related crashes (1.5.1)

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-android#221]
Getting a lot of these related crashes:

```
java.lang.UnknownError: unexpected end of file in bencoded string
at com.frostwire.jlibtorrent.swig.libtorrent_jni.new_torrent_info__SWIG_3(Native Method)
at com.frostwire.jlibtorrent.swig.torrent_info.<init>(torrent_info.java:51)
at com.frostwire.jlibtorrent.TorrentInfo.<init>(TorrentInfo.java:32)
at com.frostwire.bittorrent.BTEngine$RestoreDownloadTask.run(BTEngine.java:911)
at com.frostwire.bittorrent.BTEngine.runNextRestoreDownloadTask(BTEngine.java:805)
at com.frostwire.bittorrent.BTEngine.restoreDownloads(BTEngine.java:642)
at com.frostwire.android.gui.transfers.TransferManager.loadTorrents(TransferManager.java:294)
at com.frostwire.android.gui.transfers.TransferManager.<init>(TransferManager.java:91)
at com.frostwire.android.gui.transfers.TransferManager.instance(TransferManager.java:77)
at com.frostwire.android.gui.transfers.Transfers.getIncompleteFiles(Transfers.java:53)
at com.frostwire.android.gui.transfers.Transfers.getIgnorableFiles(Transfers.java:65)
at com.frostwire.android.gui.Librarian.syncMediaStoreSupport(Librarian.java:512)
at com.frostwire.android.gui.Librarian.access$100(Librarian.java:72)
at com.frostwire.android.gui.Librarian$2.run(Librarian.java:346)
at java.lang.Thread.run(Thread.java:841)
```

```
java.lang.UnknownError: expected value (list, dict, int or string) in bencoded string
at com.frostwire.jlibtorrent.swig.libtorrent_jni.new_torrent_info__SWIG_3(Native Method)
at com.frostwire.jlibtorrent.swig.torrent_info.<init>(torrent_info.java:51)
at com.frostwire.jlibtorrent.TorrentInfo.<init>(TorrentInfo.java:32)
at com.frostwire.bittorrent.BTEngine$RestoreDownloadTask.run(BTEngine.java:911)
at com.frostwire.bittorrent.BTEngine.runNextRestoreDownloadTask(BTEngine.java:805)
at com.frostwire.bittorrent.BTEngine.access$500(BTEngine.java:49)
at com.frostwire.bittorrent.BTEngine$RestoreDownloadTask.run(BTEngine.java:926)
at com.frostwire.bittorrent.BTEngine.runNextRestoreDownloadTask(BTEngine.java:805)
at com.frostwire.bittorrent.BTEngine.access$500(BTEngine.java:49)
at com.frostwire.bittorrent.BTEngine$RestoreDownloadTask.run(BTEngine.java:926)
at com.frostwire.bittorrent.BTEngine.runNextRestoreDownloadTask(BTEngine.java:805)
at com.frostwire.bittorrent.BTEngine.access$500(BTEngine.java:49)
at com.frostwire.bittorrent.BTEngine$RestoreDownloadTask.run(BTEngine.java:926)
at com.frostwire.bittorrent.BTEngine.runNextRestoreDownloadTask(BTEngine.java:805)
at com.frostwire.bittorrent.BTEngine.access$500(BTEngine.java:49)
at com.frostwire.bittorrent.BTEngine$RestoreDownloadTask.run(BTEngine.java:926)
at com.frostwire.bittorrent.BTEngine.runNextRestoreDownloadTask(BTEngine.java:805)
at com.frostwire.bittorrent.BTEngine.access$500(BTEngine.java:49)
at com.frostwire.bittorrent.BTEngine$RestoreDownloadTask.run(BTEngine.java:926)
at com.frostwire.bittorrent.BTEngine.runNextRestoreDownloadTask(BTEngine.java:805)
at com.frostwire.bittorrent.BTEngine.access$500(BTEngine.java:49)
at com.frostwire.bittorrent.BTEngine$RestoreDownloadTask.run(BTEngine.java:926)
at com.frostwire.bittorrent.BTEngine.runNextRestoreDownloadTask(BTEngine.java:805)
at com.frostwire.bittorrent.BTEngine.access$500(BTEngine.java:49)
at com.frostwire.bittorrent.BTEngine$RestoreDownloadTask.run(BTEngine.java:926)
at com.frostwire.bittorrent.BTEngine.runNextRestoreDownloadTask(BTEngine.java:805)
at com.frostwire.bittorrent.BTEngine.restoreDownloads(BTEngine.java:642)
at com.frostwire.android.gui.transfers.TransferManager.loadTorrents(TransferManager.java:294)
at com.frostwire.android.gui.transfers.TransferManager.<init>(TransferManager.java:91)
at com.frostwire.android.gui.transfers.TransferManager.instance(TransferManager.java:77)
at com.frostwire.android.gui.transfers.Transfers.getIncompleteFiles(Transfers.java:53)
at com.frostwire.android.gui.transfers.Transfers.getIgnorableFiles(Transfers.java:65)
at com.frostwire.android.gui.Librarian.syncMediaStoreSupport(Librarian.java:512)
at com.frostwire.android.gui.Librarian.access$100(Librarian.java:72)
at com.frostwire.android.gui.Librarian$2.run(Librarian.java:346)
at java.lang.Thread.run(Thread.java:856)
```

```
java.lang.UnknownError: Success
at com.frostwire.jlibtorrent.swig.libtorrent_jni.new_torrent_info__SWIG_3(Native Method)
at com.frostwire.jlibtorrent.swig.torrent_info.<init>(torrent_info.java:49)
at com.frostwire.jlibtorrent.TorrentInfo.<init>(TorrentInfo.java:32)
at com.frostwire.bittorrent.BTEngine$RestoreDownloadTask.run(BTEngine.java:818)
at com.frostwire.bittorrent.BTEngine.runNextRestoreDownloadTask(BTEngine.java:768)
at com.frostwire.bittorrent.BTEngine.restoreDownloads(BTEngine.java:610)
at com.frostwire.android.gui.transfers.TransferManager.loadTorrents(TransferManager.java:294)
at com.frostwire.android.gui.transfers.TransferManager.<init>(TransferManager.java:91)
at com.frostwire.android.gui.transfers.TransferManager.instance(TransferManager.java:77)
at com.frostwire.android.gui.transfers.Transfers.getIncompleteFiles(Transfers.java:53)
at com.frostwire.android.gui.transfers.Transfers.getIgnorableFiles(Transfers.java:65)
at com.frostwire.android.gui.Librarian.syncMediaStoreSupport(Librarian.java:507)
at com.frostwire.android.gui.Librarian.access$100(Librarian.java:71)
at com.frostwire.android.gui.Librarian$2.run(Librarian.java:341)
at java.lang.Thread.run(Thread.java:864)
```

**Comment by gubatron** [comment]
@aldenml I think this is the cause for crash complains we're getting on Google play reviews.
