### ISSUE TITLE
SQL escaping issue when creating playlists

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-android#228]
should be a simple fix. Any volunteers?

```
android.database.sqlite.SQLiteException: near "s": syntax error (Sqlite code 1): , while compiling: SELECT name FROM audio_playlists WHERE (name = 'Trish's music'), (OS error - 22:Invalid argument)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:181)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:422)
at android.content.ContentResolver.query(ContentResolver.java:473)
at android.content.ContentResolver.query(ContentResolver.java:410)
at com.andrew.apollo.utils.MusicUtils.createPlaylist(MusicUtils.java:873)
at com.frostwire.android.gui.adapters.menu.CreateNewPlaylistMenuAction.onClickCreatePlaylistButton(CreateNewPlaylistMenuAction.java:86)
at com.frostwire.android.gui.adapters.menu.CreateNewPlaylistMenuAction.access$000(CreateNewPlaylistMenuAction.java:39)
at com.frostwire.android.gui.adapters.menu.CreateNewPlaylistMenuAction$1.onClick(CreateNewPlaylistMenuAction.java:76)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5272)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by gubatron** [comment]
bam!
