### ISSUE TITLE
[CRASH] Player / Index out of bounds setting repeat mode on empty playlist.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-android#252]
```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at com.andrew.apollo.MusicPlaybackService.getNextPosition(MusicPlaybackService.java:1170)
at com.andrew.apollo.MusicPlaybackService.setNextTrack(MusicPlaybackService.java:1200)
at com.andrew.apollo.MusicPlaybackService.setRepeatMode(MusicPlaybackService.java:2197)
at com.andrew.apollo.MusicPlaybackService$ServiceStub.setRepeatMode(MusicPlaybackService.java:2870)
at com.andrew.apollo.utils.MusicUtils.cycleRepeat(MusicUtils.java:254)
at com.andrew.apollo.widgets.RepeatButton.onClick(RepeatButton.java:78)
at android.view.View.performClick(View.java:4428)
at android.view.View$PerformClick.run(View.java:18436)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5082)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:782)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:598)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by aldenml** [comment]
apollo master :)

**Comment by gubatron** [comment]
haha, FrostWire is now crash free, now we'll be able to see these crashes come up, now they can use the player.
