### ISSUE TITLE
[ANR] possibly caused by com.frostwire.jlibtorrent.swig.libtorrent_jni.session_handle_wait_for_alert

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-android#253]
```
"Session-alertsLoop" daemon prio=5 tid=13 Native
| group="main" sCount=1 dsCount=0 obj=0x12c073a0 self=0xb72ab8e0
| sysTid=16483 nice=0 cgrp=default sched=0/0 handle=0xb72abdc0
| state=S schedstat=( 0 0 0 ) utm=385 stm=91 core=0 HZ=100
| stack=0xa2d04000-0xa2d06000 stackSize=1036KB
| held mutexes=
kernel: (couldn't read /proc/self/task/16483/stack)
native: #00 pc 00012960 /system/lib/libc.so (syscall+28)
native: #01 pc 000aa063 /system/lib/libart.so (art::ConditionVariable::Wait(art::Thread*)+98)
native: #02 pc 002929cf /system/lib/libart.so (art::GoToRunnable(art::Thread*)+798)
native: #03 pc 00087821 /system/lib/libart.so (art::JniMethodEnd(unsigned int, art::Thread*)+16)
native: #04 pc 0018a9a5 /data/dalvik-cache/arm/data@app@com.frostwire.android-1@base.apk@classes.dex (Java_com_frostwire_jlibtorrent_swig_libtorrent_1jni_session_1handle_1wait_1for_1alert__JLcom_frostwire_jlibtorrent_swig_session_1handle_2JLcom_frostwire_jlibtorrent_swig_high_1resolution_1clock_00024duration_2+176)
at com.frostwire.jlibtorrent.swig.libtorrent_jni.session_handle_wait_for_alert(Native method)
at com.frostwire.jlibtorrent.swig.session_handle.wait_for_alert(session_handle.java:247)
at com.frostwire.jlibtorrent.Session$1.run(Session.java:906)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by aldenml** [comment]
I think this thread will apear in every ANR, since it's just a log of every thread.

**Comment by gubatron** [comment]
yup, just a hint, therefore the "possibly" :)
