### ISSUE TITLE
[CRASH] IllegalStateException: Unknown URL - MusicUtils.addToPlaylist()

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-android#256]
Application version: 1.6.1
Android version: Android 4.4
```
java.lang.IllegalStateException: Unknown URL: content://media/external/audio/playlists/-1/members
at android.os.Parcel.readException(Parcel.java:1473)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:413)
at android.content.ContentResolver.query(ContentResolver.java:464)
at android.content.ContentResolver.query(ContentResolver.java:407)
at com.andrew.apollo.utils.MusicUtils.addToPlaylist(MusicUtils.java:937)
at com.frostwire.android.gui.adapters.menu.CreateNewPlaylistMenuAction.onClickCreatePlaylistButton(CreateNewPlaylistMenuAction.java:90)
at com.frostwire.android.gui.adapters.menu.CreateNewPlaylistMenuAction.access$000(CreateNewPlaylistMenuAction.java:39)
at com.frostwire.android.gui.adapters.menu.CreateNewPlaylistMenuAction$1.onClick(CreateNewPlaylistMenuAction.java:76)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Jaymo** [comment]
Were you able to solve this?

**Comment by gubatron** [comment]
I believe so.

**Comment by Jaymo** [comment]
would you mind sharing how..I have the same fork implemented on a project here https://github.com/Jaymo/TIMBY/blob/master/src/net/micode/soundrecorder/SoundRecorder.java

**Comment by gubatron** [comment]
I think I just simply catch the exception when the URI doesn't make any sense.
`content://media/external/audio/playlists/-1/`

**Comment by gubatron** [comment]
yup, that was it, look:

```java
/**
     * @param context The {@link Context} to use.
     * @param ids The id of the song(s) to add.
     * @param playlistid The id of the playlist being added to.
     */
    public static void addToPlaylist(final Context context, final long[] ids, final long playlistid) {
        if (ids == null) {
            LOG.warn("song ids given null, not adding anything to playlist.");
            return;
        }

        if (ids == sEmptyList) {
            LOG.warn("song ids was empty, not adding anything to playlist.");
            return;
        }

        final int size = ids.length;
        final ContentResolver resolver = context.getContentResolver();
        final String[] projection = new String[] {
            "count(*)"
        };
        final Uri uri = MediaStore.Audio.Playlists.Members.getContentUri("external", playlistid);
        Cursor cursor = null;
        try {
            cursor = resolver.query(uri, projection, null, null, null);
        } catch (Throwable ignored) {}

        if (cursor != null) {
            cursor.moveToFirst();
            final int base = cursor.getInt(0);
            cursor.close();
            int numinserted = 0;
            for (int offSet = 0; offSet < size; offSet += 1000) {
                makeInsertItems(ids, offSet, 1000, base);
                numinserted += resolver.bulkInsert(uri, mContentValuesCache);
            }
            final String message = context.getResources().getQuantityString(
                    R.plurals.NNNtrackstoplaylist, numinserted, numinserted);
            AppMsg.makeText(context, message, AppMsg.STYLE_CONFIRM).show();
        } else {
            LOG.warn("Unable to complete addToPlaylist, review the logic");
        }
    }
```

**Comment by Jaymo** [comment]
Trying the fix out
