### ISSUE TITLE
[CRASH-Android-6] Permission Denial: reading com.android.providers.media.MediaProvider 

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-android#264]
Here we go... 

CC: @kad3mlia @aldenml @muckachina 

```
Process: com.frostwire.android, PID: 1533
    java.lang.RuntimeException: Unable to create service com.andrew.apollo.MusicPlaybackService: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/fs_id from pid=1533, uid=10057 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
            at android.app.ActivityThread.-wrap4(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/fs_id from pid=1533, uid=10057 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
            at android.os.Parcel.readException(Parcel.java:1599)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
            at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
            at android.content.ContentResolver.query(ContentResolver.java:491)
            at android.content.ContentResolver.query(ContentResolver.java:434)
            at com.andrew.apollo.MusicPlaybackService.getCardId(MusicPlaybackService.java:800)
            at com.andrew.apollo.MusicPlaybackService.onCreate(MusicPlaybackService.java:557)
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
            at android.app.ActivityThread.-wrap4(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by gubatron** [comment]
So here we go. I'll just leave this for educational purposes as I try to solve the problem.

Starting Android 6, permissions are grouped into Normal Permissions and Dangerous Permissions.
Normal permissions are granted by the system automatically, Dangerous ones need to be explicitely approved granularly by the user to the app.

Of the list of Dangerous Permissions FrostWire has the the following ones:

 * WRITE_EXTERNAL_STORAGE
 * READ_EXTERNAL_STORAGE
(FrostWire needs to write the bytes it downloads, most users want to put their files on external storage if they have SD cards in order to store large files.)

 * READ_PHONE_STATE
(FrostWire needs to be able to pause the music player if a call is coming in, otherwise the user would hear music as he tries to speak and would have to manually go back to FrostWire and pause the application before or during the call, which would be really annoying.)

**Comment by gubatron** [comment]
[started playing with Android 6 permissions](https://github.com/gubatron/frostwire-android/commit/7c86dd29eafb4d4723efcf8ca358ef79c1d2b61e)

**Comment by aldenml** [comment]
It's ok to start exploring the Android 6 permission framework, but this particular error is there since at least a few months ago. It is related to `MusicPlaybackService.getCardId` and I think we can(should) fix it just by somehow avoiding it.

**Comment by gubatron** [comment]
yes, in the process I've noticed a weird behavior/design with the music playback service, perhaps to save battery or what not, but it sets up a timer for an automatic shutdown if it finds itself idle for one minute.

I think the way the android engineers setup this whole permission thing is pretty elegant and simple (at least in theory), will tell you more about it in person.

**Comment by sunshinetpu** [comment]
It will crash if you set your targetSDK = 23. But in my project, I set target SDK = 21. So that means by default all permission are granted. Why do I still get this exception?

**Comment by gubatron** [comment]
maybe because you're running Android 6?
Go to settings, apps, frostwire and check the new permissions section.

**Comment by isometriq** [comment]
Solution for supporting the new permissions model
https://androidhub.intel.com/posts/blundell/You_have_permission_to.html

**Comment by gubatron** [comment]
thanks @isometriq we implemented this back in November
