### ISSUE TITLE
Kindle-NPE - AudioPlayerActivity.startPlayback -> apollo.NotificationHelper.buildNotification : 102

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-android#72]
```bash
java.lang.NullPointerException
    at android.widget.RemoteViews$ReflectionAction.writeToParcel(RemoteViews.java:763)
    at android.widget.RemoteViews.writeToParcel(RemoteViews.java:1654)
    at android.app.Notification.writeToParcel(Notification.java:534)
    at android.app.ActivityManagerProxy.setServiceForeground(ActivityManagerNative.java:2337)
    at android.app.Service.startForeground(Service.java:631)
    at com.andrew.apollo.NotificationHelper.buildNotification(NotificationHelper.java:102)
    at com.andrew.apollo.MusicPlaybackService.updateNotification(MusicPlaybackService.java:791)
    at com.andrew.apollo.MusicPlaybackService.play(MusicPlaybackService.java:1987)
    at com.andrew.apollo.MusicPlaybackService$ServiceStub.play(MusicPlaybackService.java:2746)
    at com.andrew.apollo.utils.MusicUtils.playFile(MusicUtils.java:602)
    at com.frostwire.android.gui.activities.AudioPlayerActivity.startPlayback(AudioPlayerActivity.java:594)
    at com.frostwire.android.gui.activities.AudioPlayerActivity.onServiceConnected(AudioPlayerActivity.java:250)
    at com.andrew.apollo.utils.MusicUtils$ServiceBinder.onServiceConnected(MusicUtils.java:138)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1112)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1129)
    at android.os.Handler.handleCallback(Handler.java:605)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4558)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
    at dalvik.system.NativeStart.main(Native Method)```

**Comment by cheako** [comment]
I'm unable to find the definition of R.drawable.frostwire_notification an oversight?

**Comment by cheako** [comment]
throw new NullPointerException(
                     String.format("%1$s: %2$s: (%3$s,%4$s,%5$s,%6$d,%7$b)",
                     getClass().getName(), mService.getPackageName(),
                     albumName, artistName, trackName, albumId, isPlaying));

            throw new NullPointerException(getClass().getName() + ": " +
                     mService.getPackageName() + " (" +
                     albumName + ", " + artistName...
